### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Sm4rty-1**
Referring to this [Tweet](https://twitter.com/z0age/status/1533807646372876288), my contribution got merged here (hope this counts): https://github.com/ProjectOpenSea/seaport/pull/336

### CODE REVIEW

**Comment by 0age** [comment]
Could you remove the twitter link from the ENS column?

**Comment by Sm4rty-1** [comment]
Yes, I did removed it.

**Comment by 0age** [comment]
Note that the linked PR actually has failing tests (forge + coverage tests); feel free to take a stab at implementing and getting tests to pass!

**Comment by 0age** [comment]
Closing, feel free to reopen with a working implementation of the contribution you referenced above!

**Pull request closed without merging**
