### PR TITLE
Enforce style prefix increment and postfix increment

### PR DESCRIPTION
**Pull request by eugenioclrc**
## Motivation

The difference between the prefix increment and postfix increment expression lies in the return value of the expression.

The prefix increment expression (`++i`) returns the updated value after it's incremented. The postfix increment expression (`i++`) returns the original value.

The prefix increment expression is cheaper in terms of gas.

Consider using the prefix increment expression whenever the return value is not needed.

Note to be careful using this optimization whenever the expression's return value is used afterwards, e.g. `uint a = i++` and `uint a = ++i` result in different values for `a`.

### CODE REVIEW

**Comment by 0age** [comment]
mind running `yarn lint:fix` and commiting that?

**Comment by eugenioclrc** [comment]
Ready!

**Comment by 0age** [comment]
Looks like another PR implemented this same thing ahead of yours, though yours has been open for a minute; want to close this one and just open another adding yourself as a contributor?

**Comment by eugenioclrc** [comment]
@0age they frontrun me!!! we need a zero kwnoledge github LOL

**Pull request closed without merging**
