### PR TITLE
[UPD] GAS optimisations / DRY

### PR DESCRIPTION
**Pull request by johnashu**
Gas optimisations and DRY standards.

Remove length from loops

Remove declarations out of loops (except `contracts/helpers/TransferHelper.sol` - handled here #1261 )

Abstract duplicate code into DRY functions

Better naming for 'items'

### CODE REVIEW

**Comment by johnashu** [comment]
@0age Can you trigger the workflow again?

**Comment by johnashu** [comment]
@0age Is this up for review? Is there anything I need to do?

**Comment by ryanio** [comment]
i don't see an option to trigger workflow, can you push a fresh commit to see if it shows up? thanks for the PR!

**Comment by johnashu** [comment]
> i don't see an option to trigger workflow, can you push a fresh commit to see if it shows up? thanks for the PR!

Looks like I have a conflict anyhow so let me resolve that!.. It only triggered on my first commit and @0age triggered the last time..

**Comment by johnashu** [comment]
> i don't see an option to trigger workflow, can you push a fresh commit to see if it shows up? thanks for the PR!

I fixed the merge conflicts but it still does not trigger automatically :)

**Pull request closed without merging**
