### PR TITLE
Add deployment steps

### PR DESCRIPTION
**Pull request by Slokh**
Adding steps for deployments and updating table on README

### CODE REVIEW

**Comment by arr00** [comment]
Should add the address for `IMMUTABLE_CREATE2_FACTORY_ADDRESS`(`0x7a0d94f55792c434d74a40883c6ed8545e406d12`) in docs

**Comment by arr00** [comment]
`KEYLESS_CREATE2_ADDRESS` is present on many chains already. Should probably mention that they may not need to create it, check `0x7A0D94F55792C434d74a40883C6ed8545E406D12` to see if it exists

**Review by ryanio — APPROVED** [review]
lgtm

**Comment by ryanio** [comment]
> `KEYLESS_CREATE2_ADDRESS` is present on many chains already. Should probably mention that they may not need to create it, check `0x7A0D94F55792C434d74a40883C6ed8545E406D12` to see if it exists

@arr00 it does say that on the 2nd line? ```If there is no IMMUTABLE_CREATE2_FACTORY_ADDRESS on the chain, you must deploy this first.```

**Review by 0age — CHANGES_REQUESTED** [review]
Looking good! Two nits: first, let’s remove all the references to “you” (so instead of saying “you can deploy by…” just say “deploy by…”) and second, let’s include steps to verify source as well

**Comment by arr00** [comment]
> > `KEYLESS_CREATE2_ADDRESS` is present on many chains already. Should probably mention that they may not need to create it, check `0x7A0D94F55792C434d74a40883C6ed8545E406D12` to see if it exists
> 
> @arr00 it does say that on the 2nd line? `If there is no IMMUTABLE_CREATE2_FACTORY_ADDRESS on the chain, you must deploy this first.`

Nope, two different things (`0x7A0D94F55792C434d74a40883C6ed8545E406D12` and `0x0000000000ffe8b47b3e2130213b802212439497`). The new table at the top with all the addresses makes it much less confusing though so I think its good.

**Pull request merged**
